version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8080:80
    volumes:
      - ./nextcloud_data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=Pa$$l0gin
    networks:
      - my-network

  db:
    image: mariadb
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=Pa$$l0gin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=Pa$$l0gin
    volumes:
      - ./nextcloud_db:/var/lib/mysql
    networks:
      - my-network
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nextcloud_data:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextcloud
      - db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
