version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=123456
    volumes:
      - ./nextcloud_data:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mariadb
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=123456
    volumes:
      - ./nextcloud_db:/var/lib/mysql
    ports:
      - "3306:3306"
